# Generated by Django 2.2.16 on 2022-07-30 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=200, verbose_name='Текст')),
                ('deadline_on', models.DateTimeField(verbose_name='Срок выполнения(дедлайн)')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнена ли задача')),
                ('done_at', models.DateTimeField(null=True, verbose_name='Число когда задача выполнена')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Автор задачи')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ('is_done', 'deadline_on'),
            },
        ),
    ]
