name: appvelox-tasks workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        # обновление pip
        python -m pip install --upgrade pip
        # установка зависимостей
        pip install -r requirements.txt
        # установка flake8 и его плагинов
        pip install flake8 pep8-naming flake8-broken-line flake8-return
    - name: Run unittests
      run: |
        # переход по директории appvelox
        cd appvelox
        # запуск юниттестов
        python manage.py test
        # выход из директории appvelox
        cd ..
    - name: Test tasks with flake8
      run: |
        # запуск проверки проекта по flake8
        python -m flake8
  send_message:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.workflow }} успешно выполнен!
